name: cosmic_explorer
description: "Cosmic Explorer"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  http: ^1.4.0
  yaru: ^8.0.0
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  flutter_earth_globe: ^1.0.5
  flutter_circular_text: ^0.3.1
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.0
  drift_dev: ^2.26.1

flutter:

  uses-material-design: true

  assets:
    - assets/planets/