name: cosmic-explorer
version: '1.0.0'
license: GPL-3.0-only
icon: snap/gui/cosmic-explorer.svg
title: Cosmic Explorer
summary: Explore the universe with interactive planetary visualizations
description: |
  Cosmic Explorer is a Flutter-based desktop application that allows users to explore
  detailed information about the planets in the solar system through interactive 3D visualizations.

  Ideal for astronomy enthusiasts, educators, and curious minds, it brings the solar system
  to life with real-time visuals, planetary data, and a modern UI experience.

source-code: https://github.com/romavicdosanjos/cosmic_explorer
issues: https://github.com/romavicdosanjos/cosmic_explorer/issues

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  cosmic-explorer:
    command: cosmic_explorer
    extensions: [gnome]
    plugs:
      - network
    desktop: cosmic-explorer.desktop

parts:
  app-binary:
    plugin: dump
    source: build/linux/x64/release/bundle
    stage:
      - .

  desktop-entry:
    plugin: dump
    source: snap/gui
    organize:
      cosmic-explorer.desktop: cosmic-explorer.desktop
